services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
        depends_on:
            - postgres
    postgres:
        image: postgres:16
        volumes:
            - ./tmp/postgres/data:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            PGDATA: /var/lib/postgresql/data

